Remove File's Open Tab When File Deletes
zowe/zlux-editor pull request #138
Opened 2020-02-11 19:40 UTC by shivanshs9

Fixes https://github.com/zowe/zlux/issues/381

Stuffs fixed:
- [x] if a given file is opened and selected, show a snackbar saying that the file can't be deleted.
- [ ] if a given file is opened but not selected, close the tab automatically if deleted successfully.

2020-02-19 14:59 UTC, shivanshs9 commented
@1000TurquoisePogs could you please review it?
As I've mentioned in the description, this PR requires https://github.com/zowe/zlux-file-explorer/pull/62 to be merged into staging and the updated **@zlux/file-explorer** library to be used. That's why Jenkins build is failing.

2020-03-03 07:14 UTC, shivanshs9 commented
Hey @1000TurquoisePogs @DivergentEuropeans, just wanted to bring attention to this PR. Would you have some time to review it? :smile:

2020-03-17 21:33 UTC, DivergentEuropeans requested changes
Hey view my comment, thanks!

2020-03-17 21:33 UTC, DivergentEuropeans commented on webClient/src/app/editor/project-tree/project-tree.component.ts
> +        return pathAndName === `${fileContext.model.path}/${fileContext.model.fileName}`
Hey @shivanshs9 
tldr; This doesn't work.

Long: This is the right way of doing things, however we don't delete files from the Editor control, we delete files from the right click menu (File Explorer).

The "delete" option this is referring to was when we used to have a "Delete file" menu option in the top-left menubar. However, you had to input the whole path of the file you wanted to delete and it made no sense, so we instead went for the right click option and soon to be, keyboard click, similar to Windows' Explorer. But I apologize, this is on us, when we removed that menu option, we didn't do a good job at deleting or at least commenting some of this code that is no longer used. There are tasks in our backlogs of things to go through and clean up the Editor, but other commitments we have to reach come in the way of that sometimes 🐤 

![image](https://user-images.githubusercontent.com/20528015/76903806-0b674100-6875-11ea-8e39-9ae12b6091f6.png)

2020-03-18 23:54 UTC, shivanshs9 commented on webClient/src/app/editor/project-tree/project-tree.component.ts
> +        return pathAndName === `${fileContext.model.path}/${fileContext.model.fileName}`
Hey @DivergentEuropeans 
Got it, makes more sense now why some methods are just there with a TODO. Anyways, I've implemented the delete on right click by triggering the delete event from **FileBrowserUSSComponent** all the way up to **ProjectTreeComponent**.
Can you please give some time to test it? Thanks!

2022-11-17 03:36 UTC, DivergentEuropeans commented
This has been completed in Editor V2 (v2.x/master)

2022-11-17 03:36 UTC, closed without merging