Settings menu
zowe/zlux-editor pull request #195
Opened 2021-02-04 00:49 UTC by 1000TurquoisePogs

Initial settings menu which allows for customization of builtin monaco features such as the theme, font, and text behavior.
This creates a new menu item "edit" which has the submenu "preferences".
This opens up a tab which is for editing preferences of monaco, and you will see various properties which you can control by input boxes and dropdowns.
There's 3 buttons on this menu: 
* save which saves to the config service (and applies to the editor right away, and the editor uses these settings on startup)
* preview, which takes whatever json is in the text preview area and tries to apply it, if its valid
* reset, which gets the data from the config service again, in case you didnt like your changes.

2021-02-04 00:50 UTC, 1000TurquoisePogs commented
I have the options "undo" and "redo" in the edit menu but they dont do anything yet. I'll either implement them or remove them from the PR, depending on if I have the time.

2021-02-04 05:39 UTC, lchudinov requested changes
Good work. Aside from the errors in JS console I noticed that it doesn't update Preview when I press Reset.

2021-02-04 05:39 UTC, lchudinov commented on webClient/src/app/editor/code-editor/monaco-settings/monaco-settings.component.ts
> +      this.editor.setModelLanguage('json');
I get an error in the JS console: `setModelLanguage` is not a function. 
```typescript
this.editor.updateOptions({language: 'json'});
```
should work better.

2021-02-05 06:09 UTC, lchudinov commented
When I change `LineNumbers` to `off` then Preview updates correctly. If I press `Revert` then nothing happens. If I press `Revert` second time Preview updates correctly, but the UI on the left still shows  `LineNumbers` is `off`.
![revert](https://user-images.githubusercontent.com/34669449/106996324-952c3f80-67a2-11eb-8d62-439a63b80700.gif)

2021-02-05 06:10 UTC, lchudinov requested changes

2021-02-05 06:14 UTC, lchudinov commented on webClient/src/app/editor/code-editor/monaco/monaco.component.ts
> +      console.log(this.editor);
console.log

2021-02-08 05:31 UTC, lchudinov approved these changes
Excellent work👍.  I found a couple minor issue. See my PR if they are relevant: https://github.com/1000TurquoisePogs/zlux-editor/pull/1

2021-02-08 14:11 UTC, merged