initial work to open file at a specific line using URL
zowe/zlux-editor pull request #308
Opened 2022-10-28 21:15 UTC by AdarshdeepCheema

Signed-off-by: Adarshdeep Cheema <adarshdeep.cheema@ibm.com>

## Proposed changes

This PR addresses Issue: [*Link to Github issue within https://github.com/zowe/zlux/issues* if any]

This PR depends upon the following PRs:

## Type of change
Please delete options that are not relevant.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Change in a documentation
- [ ] Refactor the code 
- [ ] Chore, repository cleanup, updates the dependencies.
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## PR Checklist
Please delete options that are not relevant.
- [ ] If the changes in this PR are meant for the next release / mainline, this PR targets the "staging" branch.
- [ ] My code follows the style guidelines of this project (see: [Contributing guideline](https://github.com/zowe/zlux/blob/master/CONTRIBUTING.md))
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] New and existing unit tests pass locally with my changes
- [ ] video or image is included if visual changes are made
- [ ] Relevant update to CHANGELOG.md
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works, or describe a test method below

## Testing

## Further comments

2022-11-08 23:13 UTC, DivergentEuropeans requested changes

2022-11-08 23:13 UTC, DivergentEuropeans commented on webClient/src/app/editor/code-editor/monaco/monaco.component.scss
> +    ::ng-deep .myLineDecoration {
I like the code here so far in the PR! Will continue scrolling down, but I think the UX could use a little work?

![image](https://user-images.githubusercontent.com/20528015/200693842-2b7460b4-5dc6-4d21-8236-537575d535c6.png)

It's pretty difficult to tell right now which line we are meant to start with especially in full-screen viewing (my thoughts: if the user doesn't know what line the URL takes them to, does the UX make it obvious which one they should be looking at?). I think something like this accomplishes it better maybe

![image](https://user-images.githubusercontent.com/20528015/200694928-47895d7f-1c35-429f-862c-caaff81d977b.png)

I also recolored it to make it distinctly different from a "selection"

`background: #e6e1ad;
 width: 50px !important;
 margin-left: -35px;`

2022-11-08 23:13 UTC, DivergentEuropeans commented on webClient/src/app/editor/code-editor/monaco/monaco.component.ts
> +        this.snackBar.open("Copied link successfully", 'Dismiss', { duration: MessageDuration.Short, panelClass: 'center' });
We probably don't need this snackbar. It's rare I see a pop-up for mouse copy actions

2022-11-08 23:13 UTC, DivergentEuropeans commented on webClient/src/app/editor/code-editor/monaco/monaco.component.ts
> +        console.error("Failed to copy link to clipboard"+ error);
But here, we probably do want one! In case things fail for some reason

2022-11-08 23:13 UTC, DivergentEuropeans commented on webClient/src/app/editor/code-editor/monaco/monaco.component.ts
> +        this.snackBar.open("Copied line successfully", 'Dismiss', { duration: MessageDuration.Short, panelClass: 'center' });
We probably don't need this snackbar. It's rare I see a pop-up for mouse copy actions

2022-11-08 23:13 UTC, DivergentEuropeans commented on webClient/src/app/editor/code-editor/monaco/monaco.component.ts
> +        console.error("Failed to copy link to clipboard"+ error);
But here, we probably do want one! In case things fail for some reason

2022-11-17 03:22 UTC, DivergentEuropeans requested changes
I'm not able to remove the highlight from the page once it's on there. I can remove it, if the line is empty but if I delete the line, and type over it, the highlight comes back. The highlight can also be shifted around using linebreaks (see screenshot). I think you're opening a can of worms here to bug test this UX, I would recommend just sticking to highlighting the line number instead of the line itself. The rest of the PR I love, the UX just feels buggy

![image](https://user-images.githubusercontent.com/20528015/202346903-d2a00dbd-2870-41fc-878a-e0ce992ab4f8.png)

2022-11-17 03:37 UTC, DivergentEuropeans commented
I think you resolved this but forgot to remove the 2nd snackbar:
https://github.com/zowe/zlux-editor/pull/308/files#diff-f1f6be017c15d827097c4d23b9480ce78315847ff3006f848c770c1cbed1eeebR278

2022-11-17 16:16 UTC, AdarshdeepCheema commented
> I'm not able to remove the highlight from the page once it's on there. I can remove it, if the line is empty but if I delete the line, and type over it, the highlight comes back. The highlight can also be shifted around using linebreaks (see screenshot). I think you're opening a can of worms here to bug test this UX, I would recommend just sticking to highlighting the line number instead of the line itself. The rest of the PR I love, the UX just feels buggy
> 
> ![image](https://user-images.githubusercontent.com/20528015/202346903-d2a00dbd-2870-41fc-878a-e0ce992ab4f8.png)

Changed the decoration to the line number instead of line content and now we will remove the decoration if the user tries to edit the file

2022-11-17 16:16 UTC, AdarshdeepCheema commented
> I think you resolved this but forgot to remove the 2nd snackbar: https://github.com/zowe/zlux-editor/pull/308/files#diff-f1f6be017c15d827097c4d23b9480ce78315847ff3006f848c770c1cbed1eeebR278

Fixed/Removed

2022-11-26 23:36 UTC, DivergentEuropeans approved these changes
Changes addressed, this looks great. We just need to document this now @AdarshdeepCheema

2022-11-26 23:37 UTC, merged